version: "3.8"

services:
  backend:
    container_name: repogrep_backend
    restart: always
    image: repogrep/backend:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - backend/src/config/.env
    volumes:
      - ./backend/logs:/usr/src/app/logs
      - ./backend/backup:/usr/src/app/backup
    networks:
      - shared-network
  frontend:
    container_name: repogrep_frontend
    restart: always
    image: repogrep/frontend:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network

networks:
  shared-network: